[package]
name = "wpaperd"
version = "0.1.0"
edition = "2021"
authors = ["Danilo Spinella <danilo.spinella@suse.com>"]
description = "Wallpaper daemon for Wayland"
readme = "README.md"
homepage = "https://github.com/danyspin97/wpaperd"
repository = "https://github.com/danyspin97/wpaperd"
license = "GPL-3.0+"
keywords = ["wallpaper", "wayland", "wlroots"]
categories = ["command-line-utilities", "multimedia"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calloop = "0.9.3"
clap = { version = "3.1.5", features = ["derive", "wrap_help"] }
color-eyre = "0.6.1"
dowser = "0.3.6"
flexi_logger = "0.22.3"
image = "0.24.1"
hotwatch = "0.4.6"
humantime-serde = "1.0.1"
lazy_static = "1.4.0"
log = "0.4.14"
mime = "0.3.16"
new_mime_guess = "4.0.1"
nix = "0.23.1"
rand = "0.8.5"
serde = { version = "1.0.136", features = ["derive", "rc"] }
smithay-client-toolkit = "0.15.3"
timer = { git = "https://github.com/danyspin97/timer.rs" }
toml = "0.5.8"
wayland-client = "0.29.4"
xdg = "2.4.1"

[build-dependencies]
clap = { version = "3.1.5", features = ["derive", "cargo", "env"] }
clap_complete = "3.1.1"
clap_mangen = "0.1.2"
# used for the imports in src/config.rs
serde = { version = "1.0.136", features = ["derive"] }
